### ISSUE TITLE
If Json-ld is selected hide Yoast and other options

### ISSUE THREAD

**Issue by timvaniersel** [Websitescanner/remove-schema#2]
If JSON-ld is selected to be removed deselect and hide Yoast and Woocommerce remove schema options.

**Comment by githubuser441** [comment]
I was thinking of Creating like a section in the admin with plugin/theme schema's to turn off. And a seperate section like "Aggressive schema removal" to remove all schema.

**Comment by timvaniersel** [comment]
If pull request #12 is accepted this issue can be closed. Rest of the issue will be done in #6
