### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by timvaniersel** [Websitescanner/remove-schema#4]
- [x] Installation
- [x] Support
- [x] Contributions

**Comment by githubuser441** [comment]
Should I setup a simple wordpress site to make a guide on how to use the plugin?

**Comment by timvaniersel** [comment]
@coollorenzo That would be nice! 
Can you also add your WordPress username to the contributors in `README.txt`?

**Comment by githubuser441** [comment]
I created a Wordpress website for remove-schema: https://remove-schema.com/
This gives us more posibility to explain the functionallity with a extensive knowledge base and seperate support email. Which also makes it easier to handle issue's and marketing together.

I will sent you credentials for WP and email via messenger :)
