### ISSUE TITLE
Remove schema on a page specific level

### ISSUE THREAD

**Issue by githubuser441** [Websitescanner/remove-schema#8]
Good for pages which have problems with certain schema settings. Also great if you only want to remove schema on specific pages to test the seo benefits.

**Comment by timvaniersel** [comment]
There are a lot of possibilities on how you could implement this. 

1. Disable (or enable) all the plugin functions on a page by checking a box on the page editor
2. Have a list of all the schema generating plugins for each page that you can check or uncheck.

What kind of solution are you thinking about?

**Comment by githubuser441** [comment]
@timvaniersel I made both, but you can't exclude specific schema's on a page. Only remove specific schema or a option to not remove any schema. Please review PR #10

**Comment by githubuser441** [comment]
@timvaniersel I think you can close this issue now #10 is merged
